"""
Data loading, normalisation and rolling-forward train/val/test splitting.

Supports two data formats:
  1. **Sample data** – single merged prices CSV + single news CSV with pre-embedded
     vectors (generated by ``src/data/generate_sample.py``).
  2. **Real data** – separate per-mineral CSVs in ``src/data/dataset/``:
     ``trading-data-{mineral}.csv`` and ``news-summary-{mineral}.csv``.
     Use ``load_prices_real`` / ``load_news_real`` / ``build_news_tensor_real``.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass
from typing import Callable, List, Optional, Tuple

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Normaliser
# ─────────────────────────────────────────────────────────────────────────────

class Normalizer:
    """Per-mineral z-score or min-max normaliser fitted on training data only."""

    def __init__(self, method: str = "zscore"):
        if method not in ("zscore", "minmax"):
            raise ValueError(f"Unknown normalization method: {method!r}")
        self.method = method
        self._params: dict[str, dict[str, float]] = {}

    def fit(self, df: pd.DataFrame, minerals: List[str]) -> "Normalizer":
        for m in minerals:
            if self.method == "zscore":
                self._params[m] = {"mean": float(df[m].mean()), "std": float(df[m].std()) or 1.0}
            else:
                self._params[m] = {"min": float(df[m].min()), "max": float(df[m].max()) or 1.0}
        return self

    def transform(self, df: pd.DataFrame, minerals: List[str]) -> pd.DataFrame:
        df = df.copy()
        for m in minerals:
            p = self._params[m]
            if self.method == "zscore":
                df[m] = (df[m] - p["mean"]) / p["std"]
            else:
                df[m] = (df[m] - p["min"]) / (p["max"] - p["min"])
        return df

    def inverse_transform(self, arr: np.ndarray, mineral_idx: int, mineral: str) -> np.ndarray:
        """Invert normalisation for a single mineral column."""
        p = self._params[mineral]
        if self.method == "zscore":
            return arr * p["std"] + p["mean"]
        return arr * (p["max"] - p["min"]) + p["min"]

    def inverse_transform_all(self, arr: np.ndarray, minerals: List[str]) -> np.ndarray:
        """
        Invert normalisation for all minerals.

        arr: shape (..., len(minerals))
        """
        out = arr.copy()
        for i, m in enumerate(minerals):
            out[..., i] = self.inverse_transform(arr[..., i], i, m)
        return out


# ─────────────────────────────────────────────────────────────────────────────
# Data loading
# ─────────────────────────────────────────────────────────────────────────────

def load_prices(path: str, minerals: List[str]) -> pd.DataFrame:
    """Load and minimally validate the price CSV."""
    df = pd.read_csv(path, parse_dates=["date"])
    df = df.sort_values("date").reset_index(drop=True)
    for m in minerals:
        if m not in df.columns:
            raise ValueError(f"Column '{m}' not found in prices file")
    # Fill weekends / holidays with linear interpolation
    df[minerals] = df[minerals].interpolate(method="linear", limit_direction="both")
    return df


def load_news(path: str) -> pd.DataFrame:
    """Load news embeddings. Each cell is a comma-separated float string."""
    df = pd.read_csv(path, parse_dates=["date"])
    df = df.sort_values(["date", "mineral"]).reset_index(drop=True)
    return df


def _parse_embed(cell: str) -> np.ndarray:
    """Convert a comma-separated float string to a numpy array."""
    return np.fromstring(cell, sep=",", dtype=np.float32)


def build_news_tensor(
    news_df: pd.DataFrame,
    dates: pd.DatetimeIndex,
    minerals: List[str],
    embed_dim: int,
) -> np.ndarray:
    """
    Build a news embedding array aligned to *dates*.

    Returns shape (len(dates), n_minerals, 3, embed_dim)
    where axis-2 is [short, medium, long].
    """
    n = len(dates)
    n_min = len(minerals)
    tensor = np.zeros((n, n_min, 3, embed_dim), dtype=np.float32)

    # Index news by (date, mineral) for fast lookup
    news_idx = news_df.set_index(["date", "mineral"])

    for i, d in enumerate(dates):
        for j, m in enumerate(minerals):
            try:
                row = news_idx.loc[(d, m)]
            except KeyError:
                continue
            tensor[i, j, 0] = _parse_embed(row["summary_short"])
            tensor[i, j, 1] = _parse_embed(row["summary_medium"])
            tensor[i, j, 2] = _parse_embed(row["summary_long"])

    return tensor


# ─────────────────────────────────────────────────────────────────────────────
# Rolling-forward split
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DataSplit:
    """Indices (into the full sorted date array) for one train/val/test split."""
    train: Tuple[int, int]  # [start, end)
    val:   Tuple[int, int]
    test:  Tuple[int, int]


def make_rolling_splits(
    n_total: int,
    train_ratio: float = 0.60,
    val_ratio: float = 0.20,
    test_ratio: float = 0.20,
    roll_step: int = 30,
    lookback: int = 180,
    max_horizon: int = 180,
) -> List[DataSplit]:
    """
    Generate a list of rolling-forward splits.

    The first split uses the first *train_ratio* of data for training, the
    next *val_ratio* for validation, and the next *test_ratio* for testing.
    Subsequent splits advance by *roll_step* days.

    Only the first split is returned unless there is enough data to advance.
    """
    splits: List[DataSplit] = []

    train_len = int(n_total * train_ratio)
    val_len   = int(n_total * val_ratio)
    test_len  = int(n_total * test_ratio)

    offset = 0
    while True:
        tr_start = offset
        tr_end   = offset + train_len
        va_start = tr_end
        va_end   = va_start + val_len
        te_start = va_end
        te_end   = te_start + test_len

        if te_end > n_total:
            break

        # Ensure the test window is large enough to form at least one sample
        if (te_end - te_start) < (lookback + max_horizon):
            break

        splits.append(DataSplit(
            train=(tr_start, tr_end),
            val=(va_start, va_end),
            test=(te_start, te_end),
        ))

        offset += roll_step
        # Stop if the initial split offset would exceed data bounds
        if tr_start + roll_step + train_len + val_len + test_len > n_total:
            break

    # Always return at least one split (the initial one)
    if not splits:
        tr_end  = train_len
        va_end  = tr_end + val_len
        te_end  = min(va_end + test_len, n_total)
        splits.append(DataSplit(
            train=(0, tr_end),
            val=(tr_end, va_end),
            test=(va_end, te_end),
        ))

    return splits


# ─────────────────────────────────────────────────────────────────────────────
# Real-data loaders (src/data/dataset/ directory)
# ─────────────────────────────────────────────────────────────────────────────

def load_prices_real(data_dir: str, minerals: List[str]) -> pd.DataFrame:
    """
    Load per-mineral trading CSVs and merge them on date.

    Reads ``trading-data-{mineral}.csv`` for each mineral, uses the ``close``
    price column, then inner-joins on ``time`` so only dates present for all
    minerals are kept.  Missing values are forward-filled.

    Returns a DataFrame with columns ``[date, *minerals]``.
    """
    frames: List[pd.DataFrame] = []
    for m in minerals:
        path = os.path.join(data_dir, f"trading-data-{m}.csv")
        df = pd.read_csv(path, parse_dates=["time"])
        df = df.rename(columns={"time": "date", "close": m})[["date", m]]
        df = df.sort_values("date").reset_index(drop=True)
        frames.append(df)

    merged = frames[0]
    for frame in frames[1:]:
        merged = merged.merge(frame, on="date", how="inner")

    merged = merged.sort_values("date").reset_index(drop=True)
    merged[minerals] = merged[minerals].interpolate(method="linear", limit_direction="both")
    return merged


# ── News text parsing ─────────────────────────────────────────────────────────

def _extract_sections(text: str) -> dict:
    """
    Extract Short/Medium/Long-term sections from a news summary text.

    Silver and Copper news rows have explicit "- Short-term:", "- Medium-term:",
    "- Long-term:" bullet points.  Gold rows use a single "- Overview:" bullet.
    When explicit sections are absent, the Overview text (or the full text) is
    used as the fallback for all three horizons.
    """
    short_m  = re.search(
        r"[-*]\s*Short[-\s]term:\s*(.*?)(?=\n\s*[-*]\s*(?:Medium|Long)[-\s]term:|\Z)",
        text, re.DOTALL | re.IGNORECASE,
    )
    medium_m = re.search(
        r"[-*]\s*Medium[-\s]term:\s*(.*?)(?=\n\s*[-*]\s*Long[-\s]term:|\Z)",
        text, re.DOTALL | re.IGNORECASE,
    )
    long_m   = re.search(
        r"[-*]\s*Long[-\s]term:\s*(.*?)(?=\n\s*\{|\Z)",
        text, re.DOTALL | re.IGNORECASE,
    )
    overview_m = re.search(
        r"[-*]\s*Overview:\s*(.*?)(?=\n\s*\{|\Z)",
        text, re.DOTALL | re.IGNORECASE,
    )

    # Build fallback from Overview (or whole text), stripping trailing JSON block
    fallback_raw = overview_m.group(1).strip() if overview_m else text
    fallback = re.split(r"\n\s*\{", fallback_raw)[0].strip()

    def _clean(m: Optional[re.Match]) -> str:  # type: ignore[type-arg]
        if m is None:
            return fallback
        t = re.split(r"\n\s*\{", m.group(1).strip())[0].strip()
        return t or fallback

    return {
        "short":  _clean(short_m),
        "medium": _clean(medium_m),
        "long":   _clean(long_m),
    }


def load_news_real(data_dir: str, minerals: List[str]) -> pd.DataFrame:
    """
    Load per-mineral news CSVs and parse Short/Medium/Long-term sections.

    Reads ``news-summary-{mineral}.csv`` for each mineral and extracts the
    three horizon-specific text summaries from the ``text`` column.

    Returns a DataFrame with columns:
      ``[start_date, end_date, mineral, text_short, text_medium, text_long]``
    sorted by ``(mineral, start_date)`` ascending.
    """
    rows: List[dict] = []
    for m in minerals:
        path = os.path.join(data_dir, f"news-summary-{m}.csv")
        df = pd.read_csv(path, parse_dates=["start_date", "end_date"])
        for _, row in df.iterrows():
            secs = _extract_sections(row["text"])
            rows.append(
                {
                    "start_date":  row["start_date"],
                    "end_date":    row["end_date"],
                    "mineral":     m,
                    "text_short":  secs["short"],
                    "text_medium": secs["medium"],
                    "text_long":   secs["long"],
                }
            )
    return (
        pd.DataFrame(rows)
        .sort_values(["mineral", "start_date"])
        .reset_index(drop=True)
    )


# ── Text embedding ────────────────────────────────────────────────────────────

def _build_text_encoder(
    all_texts: List[str],
    embed_dim: int,
) -> Callable[[List[str]], np.ndarray]:
    """
    Return a callable ``encode(texts) -> np.ndarray`` of shape ``(N, embed_dim)``.

    Tries ``sentence-transformers`` (``all-MiniLM-L6-v2``, 384-dim) first;
    falls back to TF-IDF + Truncated SVD (sklearn) if unavailable.
    """
    try:
        from sentence_transformers import SentenceTransformer  # type: ignore
        model = SentenceTransformer("all-MiniLM-L6-v2")
        log.info("Using sentence-transformers encoder (all-MiniLM-L6-v2)")

        def _st_encode(texts: List[str]) -> np.ndarray:
            return model.encode(texts, show_progress_bar=False, batch_size=32)

        return _st_encode
    except ImportError:
        pass

    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.decomposition import TruncatedSVD

    tfidf = TfidfVectorizer(max_features=10_000, ngram_range=(1, 2), sublinear_tf=True)
    tfidf.fit(all_texts)
    n_features = len(tfidf.get_feature_names_out())
    n_components = min(embed_dim, len(all_texts) - 1, n_features - 1)
    svd = TruncatedSVD(n_components=n_components, random_state=42)
    svd.fit(tfidf.transform(all_texts))
    log.info(f"Using TF-IDF + SVD encoder (n_components={n_components})")

    def _tfidf_encode(texts: List[str]) -> np.ndarray:
        X = tfidf.transform(texts)
        dense = svd.transform(X).astype(np.float32)
        if dense.shape[1] < embed_dim:
            dense = np.pad(dense, ((0, 0), (0, embed_dim - dense.shape[1])))
        return dense[:, :embed_dim]

    return _tfidf_encode


def build_news_tensor_real(
    news_df: pd.DataFrame,
    dates: pd.Series,
    minerals: List[str],
    embed_dim: int,
    cache_path: Optional[str] = None,
) -> np.ndarray:
    """
    Build the news embedding tensor for the real dataset.

    For each reference date *t* and mineral *m*, finds the most recently
    published news row where ``start_date <= t``, then embeds its
    short/medium/long summary texts.

    Parameters
    ----------
    news_df   : output of ``load_news_real``
    dates     : aligned date Series from the prices DataFrame
    minerals  : ordered list of mineral names
    embed_dim : target embedding dimension
    cache_path: optional path to a ``.npy`` file for caching the result

    Returns
    -------
    tensor : np.ndarray, shape (len(dates), n_minerals, 3, embed_dim)
    """
    if cache_path and os.path.exists(cache_path):
        log.info(f"Loading cached news tensor from {cache_path}")
        return np.load(cache_path)

    # ── Build the text encoder fitted on ALL news texts ───────────────────────
    all_texts: List[str] = (
        news_df["text_short"].tolist()
        + news_df["text_medium"].tolist()
        + news_df["text_long"].tolist()
    )
    encoder = _build_text_encoder(all_texts, embed_dim)

    # ── Embed all unique texts (deduplicated) ─────────────────────────────────
    unique_texts = list(dict.fromkeys(all_texts))
    log.info(f"Embedding {len(unique_texts)} unique news texts …")
    unique_embeddings = encoder(unique_texts)
    embed_map = {t: unique_embeddings[i] for i, t in enumerate(unique_texts)}

    # ── Build date-aligned tensor ─────────────────────────────────────────────
    n = len(dates)
    n_min = len(minerals)
    tensor = np.zeros((n, n_min, 3, embed_dim), dtype=np.float32)

    # Pre-group and sort news by mineral for fast lookups
    news_by_mineral = {
        m: news_df[news_df["mineral"] == m].sort_values("start_date")
        for m in minerals
    }

    dates_ts = pd.to_datetime(dates).values  # numpy datetime64 array

    for j, m in enumerate(minerals):
        m_news = news_by_mineral[m]
        if m_news.empty:
            continue
        starts = m_news["start_date"].values  # numpy datetime64, sorted asc

        for i, d in enumerate(dates_ts):
            # Most recent row whose start_date ≤ reference date d
            mask = starts <= d
            if not mask.any():
                continue
            idx = int(np.where(mask)[0][-1])
            row = m_news.iloc[idx]

            tensor[i, j, 0] = embed_map.get(row["text_short"],  np.zeros(embed_dim, dtype=np.float32))
            tensor[i, j, 1] = embed_map.get(row["text_medium"], np.zeros(embed_dim, dtype=np.float32))
            tensor[i, j, 2] = embed_map.get(row["text_long"],   np.zeros(embed_dim, dtype=np.float32))

    if cache_path:
        os.makedirs(os.path.dirname(os.path.abspath(cache_path)), exist_ok=True)
        np.save(cache_path, tensor)
        log.info(f"Saved news tensor cache → {cache_path}")

    return tensor
